/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyzerRouteImport } from './routes/analyzer'
import { Route as ForensicsRouteImport } from './routes/forensics'
import { Route as GeolocationRouteImport } from './routes/geolocation'
import { Route as IocRouteImport } from './routes/ioc'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ThreatIntelligenceRouteImport } from './routes/threat-intelligence'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzerRoute = AnalyzerRouteImport.update({
  id: '/analyzer',
  path: '/analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const ForensicsRoute = ForensicsRouteImport.update({
  id: '/forensics',
  path: '/forensics',
  getParentRoute: () => rootRouteImport,
} as any)
const GeolocationRoute = GeolocationRouteImport.update({
  id: '/geolocation',
  path: '/geolocation',
  getParentRoute: () => rootRouteImport,
} as any)
const IocRoute = IocRouteImport.update({
  id: '/ioc',
  path: '/ioc',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatIntelligenceRoute = ThreatIntelligenceRouteImport.update({
  id: '/threat-intelligence',
  path: '/threat-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyzer': typeof AnalyzerRoute
  '/forensics': typeof ForensicsRoute
  '/geolocation': typeof GeolocationRoute
  '/ioc': typeof IocRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/threat-intelligence': typeof ThreatIntelligenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyzer': typeof AnalyzerRoute
  '/forensics': typeof ForensicsRoute
  '/geolocation': typeof GeolocationRoute
  '/ioc': typeof IocRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/threat-intelligence': typeof ThreatIntelligenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyzer': typeof AnalyzerRoute
  '/forensics': typeof ForensicsRoute
  '/geolocation': typeof GeolocationRoute
  '/ioc': typeof IocRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/threat-intelligence': typeof ThreatIntelligenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyzer'
    | '/forensics'
    | '/geolocation'
    | '/ioc'
    | '/reports'
    | '/settings'
    | '/threat-intelligence'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyzer'
    | '/forensics'
    | '/geolocation'
    | '/ioc'
    | '/reports'
    | '/settings'
    | '/threat-intelligence'
  id:
    | '__root__'
    | '/'
    | '/analyzer'
    | '/forensics'
    | '/geolocation'
    | '/ioc'
    | '/reports'
    | '/settings'
    | '/threat-intelligence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzerRoute: typeof AnalyzerRoute
  ForensicsRoute: typeof ForensicsRoute
  GeolocationRoute: typeof GeolocationRoute
  IocRoute: typeof IocRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  ThreatIntelligenceRoute: typeof ThreatIntelligenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyzer': {
      id: '/analyzer'
      path: '/analyzer'
      fullPath: '/analyzer'
      preLoaderRoute: typeof AnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forensics': {
      id: '/forensics'
      path: '/forensics'
      fullPath: '/forensics'
      preLoaderRoute: typeof ForensicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geolocation': {
      id: '/geolocation'
      path: '/geolocation'
      fullPath: '/geolocation'
      preLoaderRoute: typeof GeolocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ioc': {
      id: '/ioc'
      path: '/ioc'
      fullPath: '/ioc'
      preLoaderRoute: typeof IocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threat-intelligence': {
      id: '/threat-intelligence'
      path: '/threat-intelligence'
      fullPath: '/threat-intelligence'
      preLoaderRoute: typeof ThreatIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzerRoute: AnalyzerRoute,
  ForensicsRoute: ForensicsRoute,
  GeolocationRoute: GeolocationRoute,
  IocRoute: IocRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  ThreatIntelligenceRoute: ThreatIntelligenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
